-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 06 Apr 2026 pada 03.42
-- Versi server: 10.4.32-MariaDB
-- Versi PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dbportal_berita`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `artikel`
--

CREATE TABLE `artikel` (
  `id_artikel` int(11) NOT NULL,
  `judul` varchar(200) DEFAULT NULL,
  `isi` text DEFAULT NULL,
  `gambar` varchar(200) DEFAULT NULL,
  `tanggal` datetime DEFAULT NULL,
  `status` enum('publish','draft') DEFAULT 'draft',
  `id_kategori` int(11) DEFAULT NULL,
  `id_user` int(11) DEFAULT NULL,
  `views` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `artikel`
--

INSERT INTO `artikel` (`id_artikel`, `judul`, `isi`, `gambar`, `tanggal`, `status`, `id_kategori`, `id_user`, `views`) VALUES
(3, 'UMKM Digital Jadi Tulang Punggung Ekonomi Indonesia 2026', 'Laporan ekonomi terbaru menunjukkan bahwa sektor UMKM yang telah go-digital menyumbang lebih dari 60% terhadap PDB nasional. Transformasi digital memungkinkan pedagang lokal menjangkau pasar internasional dengan lebih mudah melalui platform e-commerce. Pemerintah terus mendorong pelatihan literasi keuangan digital agar para pelaku usaha kecil bisa bersaing dengan brand global di era pasar bebas ini.', '1775280648_Bitter, Sweet and Fresh.jpg', '2026-04-04 07:30:48', 'publish', 6, 1, 47),
(6, 'Tren Konten Kreator Semakin Populer di Kalangan Pelajar', 'Jakarta ,  16 Maret 2026 – Profesi sebagai konten kreator kini semakin diminati oleh kalangan pelajar. Platform media sosial menjadi wadah bagi generasi muda untuk mengekspresikan kreativitas mereka melalui berbagai jenis konten.Mulai dari video hiburan, edukasi, hingga ulasan produk, konten yang dihasilkan semakin beragam. Tidak sedikit pelajar yang berhasil memperoleh penghasilan tambahan dari aktivitas tersebut. Namun, para ahli mengingatkan pentingnya menjaga etika dan kualitas konten agar tidak menimbulkan dampak negatif di masyarakat.', 'download (10).jpg', '2026-04-04 00:00:00', 'publish', 7, 1, 40),
(7, 'Revolusi AI: Gemini 1.5 Pro Kini Bisa Memproses Video Berdurasi Panjang', 'Google baru saja merilis pembaruan besar untuk model AI mereka, Gemini 1.5 Pro. Dalam update kali ini, AI tersebut mampu memahami konteks dari video berdurasi hingga 1 jam hanya dalam hitungan detik. Hal ini sangat memudahkan para konten kreator dan peneliti untuk merangkum informasi tanpa harus menonton video dari awal sampai akhir. Teknologi ini diprediksi akan mengubah cara manusia berinteraksi dengan konten multimedia di masa depan.', 'Bing Image Creator.jpg', '2026-04-04 00:00:00', 'publish', 1, NULL, 18),
(8, 'Kemenangan Dramatis Timnas Indonesia di Kualifikasi Piala Dunia', 'Stadion Gelora Bung Karno bergemuruh semalam saat Timnas Indonesia berhasil menumbangkan lawan kuat dengan skor tipis 2-1. Gol kemenangan dicetak pada menit-menit akhir melalui tendangan bebas yang sangat akurat. Dengan hasil ini, peluang Indonesia untuk lolos ke putaran final Piala Dunia semakin terbuka lebar. Pelatih menyatakan sangat bangga dengan kerja keras dan mentalitas juara yang ditunjukkan oleh para pemain muda.', 'timnas sepakbola Indonesia.jpg', '2026-04-04 00:00:00', 'publish', 2, NULL, 9),
(9, 'Pemanfaatan Teknologi Digital Meningkat di Kalangan Pelajar', 'Pasartanahtinggi, 4 April 2026 – Penggunaan teknologi digital di kalangan pelajar terus mengalami peningkatan seiring dengan berkembangnya era digital. Berbagai perangkat seperti laptop, smartphone, dan aplikasi pembelajaran kini menjadi bagian penting dalam proses belajar mengajar. Berdasarkan pengamatan di beberapa sekolah, para siswa semakin terbiasa menggunakan platform digital untuk mengakses materi pelajaran, mengerjakan tugas, hingga berkomunikasi dengan guru. Hal ini dinilai mampu meningkatkan efisiensi serta mempermudah proses pembelajaran. Salah satu guru menyampaikan bahwa pemanfaatan teknologi memberikan dampak positif, terutama dalam hal akses informasi yang lebih luas. “Siswa sekarang lebih cepat memahami materi karena bisa mencari referensi tambahan secara mandiri melalui internet,” ujarnya. Namun demikian, penggunaan teknologi juga perlu diimbangi dengan pengawasan yang tepat. Tanpa kontrol yang baik, pelajar berpotensi terdistraksi oleh konten yang tidak berkaitan dengan pembelajaran. Pihak sekolah diharapkan dapat terus memberikan edukasi mengenai penggunaan teknologi secara bijak, sehingga manfaat yang diperoleh dapat maksimal tanpa menimbulkan dampak negatif. Dengan pemanfaatan yang tepat, teknologi digital diyakini dapat menjadi sarana pendukung utama dalam menciptakan sistem pendidikan yang lebih modern dan efektif.', 'பள்ளிகளில் கல்வி நிலை___.jpg', '2026-04-04 00:00:00', 'publish', 1, NULL, 41),
(10, 'Aktivitas Masyarakat Berjalan Normal Pasca Libur Panjang', 'Pasartanahtinggi, 4 April 2026 – Aktivitas masyarakat kembali berjalan normal setelah masa libur panjang. Sejumlah sektor seperti pendidikan, perdagangan, dan transportasi kembali beroperasi seperti biasa. Masyarakat mulai kembali menjalankan rutinitas harian dengan tetap menjaga kesehatan dan keselamatan. Pemerintah juga mengimbau agar masyarakat tetap disiplin dalam menjalankan aktivitas. Kondisi ini menunjukkan stabilitas aktivitas sosial yang terus terjaga di tengah berbagai dinamika yang terjadi.', 'Kampung Ayu - Jonathan Hagard.jpg', '2026-04-04 00:00:00', 'publish', 3, NULL, 13),
(11, 'Transformasi Digital Pendidikan Meningkatkan Kualitas Pembelajaran di Indonesia', 'Jakarta, 5 April 2026 – Perkembangan teknologi digital terus membawa perubahan signifikan dalam dunia pendidikan di Indonesia. Transformasi ini tidak hanya mengubah metode pembelajaran, tetapi juga memperluas akses pendidikan bagi masyarakat di berbagai daerah. Kementerian Pendidikan mengungkapkan bahwa pemanfaatan platform digital dalam proses belajar mengajar semakin meningkat, terutama sejak beberapa tahun terakhir. Guru dan siswa kini lebih terbiasa menggunakan media pembelajaran berbasis online, seperti video interaktif, kelas virtual, dan sistem manajemen pembelajaran. Menurut para ahli, digitalisasi pendidikan memberikan banyak manfaat, di antaranya meningkatkan fleksibilitas belajar dan mempermudah distribusi materi. Siswa dapat mengakses berbagai sumber belajar kapan saja dan di mana saja, tanpa terbatas ruang dan waktu. Namun demikian, tantangan masih tetap ada. Kesenjangan akses internet di beberapa wilayah menjadi hambatan utama dalam pemerataan pendidikan digital. Selain itu, kesiapan tenaga pendidik dalam mengadopsi teknologi juga menjadi faktor penting yang perlu diperhatikan. Pemerintah terus berupaya mengatasi kendala tersebut melalui berbagai program, seperti peningkatan infrastruktur jaringan dan pelatihan bagi guru. Diharapkan, langkah ini dapat menciptakan sistem pendidikan yang lebih inklusif dan berkualitas. Dengan adanya transformasi digital, masa depan pendidikan Indonesia diharapkan semakin maju dan mampu bersaing di tingkat global.', 'AI in Early Student Assessment and Intervention.jpg', '2026-04-04 00:00:00', 'publish', 5, NULL, 4),
(12, 'Festival Musik Lokal Kembali Digelar, Disambut Antusias Ribuan Penonton', 'Bandung, 5 April 2026 – \r\n       Dunia hiburan kembali bergairah dengan digelarnya festival musik lokal yang menghadirkan berbagai musisi dari dalam negeri. Acara yang berlangsung di Lapangan Gasibu ini sukses menarik ribuan penonton dari berbagai kalangan.\r\n       Festival tersebut menampilkan beragam genre musik, mulai dari pop, rock, hingga indie. Penampilan para musisi muda menjadi daya tarik utama, dengan energi panggung yang mampu membangkitkan semangat penonton sepanjang acara.\r\n       Selain pertunjukan musik, festival ini juga menghadirkan berbagai kegiatan menarik seperti bazar kuliner, pameran seni, dan interaksi langsung dengan para kreator. Hal ini menjadikan acara tidak hanya sebagai hiburan, tetapi juga sebagai wadah apresiasi terhadap karya kreatif anak bangsa.\r\n     Salah satu pengunjung mengungkapkan bahwa acara ini menjadi momen yang dinantikan, terutama setelah berkurangnya kegiatan hiburan selama beberapa waktu terakhir. “Seru banget, bisa nonton langsung dan suasananya ramai,” ujarnya.\r\n     Pihak penyelenggara berharap kegiatan seperti ini dapat terus diadakan secara rutin untuk mendukung perkembangan industri hiburan lokal sekaligus memberikan ruang bagi talenta baru untuk tampil di hadapan publik.\r\n     Dengan antusiasme yang tinggi dari masyarakat, festival musik lokal dinilai memiliki potensi besar untuk menjadi agenda tahunan yang mampu menarik perhatian lebih luas, bahkan hingga ke tingkat nasional.', 'download (11).jpg', '2026-04-04 00:00:00', 'publish', 7, NULL, 2),
(14, 'Inovasi Kecerdasan Buatan Permudah Aktivitas Belajar dan Kerja di Era Digital', 'Jakarta, 5 April 2026 – Perkembangan teknologi kecerdasan buatan atau Artificial Intelligence (AI) terus mengalami peningkatan yang signifikan dalam beberapa tahun terakhir. Teknologi ini kini tidak hanya digunakan oleh perusahaan besar, tetapi juga telah merambah ke kehidupan sehari-hari masyarakat, termasuk di sektor pendidikan dan dunia kerja. Berbagai platform berbasis AI memungkinkan pengguna untuk menyelesaikan pekerjaan dengan lebih cepat dan efisien. Mulai dari penulisan artikel, analisis data, hingga pembuatan desain grafis dapat dilakukan secara otomatis dengan bantuan teknologi ini. Hal tersebut tentu memberikan kemudahan bagi pelajar, mahasiswa, maupun pekerja profesional dalam meningkatkan produktivitas. Namun demikian, sejumlah pakar teknologi mengingatkan bahwa penggunaan AI harus disertai dengan pemahaman yang baik. Ketergantungan berlebihan terhadap teknologi ini dikhawatirkan dapat menurunkan kemampuan berpikir kritis pengguna. Oleh karena itu, pemanfaatan AI sebaiknya tetap diimbangi dengan kemampuan analisis manusia. Ke depan, AI diprediksi akan terus berkembang dan menjadi bagian penting dalam berbagai aspek kehidupan, sehingga masyarakat diharapkan mampu beradaptasi dengan perubahan tersebut.', 'AI Is Revolutionizing How We Learn - Artificial Intelligence +.jpg', '2026-04-05 00:00:00', 'publish', 1, NULL, 1),
(15, 'Kurikulum Baru Diterapkan, Sekolah Fokus pada Penguatan Karakter dan Keterampilan Siswa', 'Bandung, 5 April 2026 – Dunia pendidikan Indonesia kembali mengalami pembaruan melalui penerapan kurikulum terbaru yang menekankan pada penguatan karakter serta keterampilan praktis siswa. Kebijakan ini mulai diterapkan secara bertahap di berbagai sekolah guna menyesuaikan kebutuhan pendidikan di era modern. Kurikulum baru ini tidak hanya berfokus pada aspek akademik, tetapi juga mengembangkan kemampuan berpikir kritis, kreativitas, kolaborasi, serta komunikasi siswa. Dalam pelaksanaannya, metode pembelajaran berbasis proyek (project-based learning) menjadi salah satu pendekatan utama yang digunakan oleh para guru. Pihak sekolah menyambut baik kebijakan ini karena dinilai mampu menciptakan suasana belajar yang lebih interaktif dan tidak monoton. Siswa didorong untuk lebih aktif dalam proses pembelajaran serta mampu mengaplikasikan ilmu yang diperoleh dalam kehidupan sehari-hari. Meski demikian, sejumlah tantangan masih dihadapi, seperti kesiapan tenaga pendidik dan fasilitas pendukung yang belum merata di seluruh daerah. Oleh karena itu, pemerintah terus melakukan pelatihan bagi guru serta meningkatkan sarana dan prasarana pendidikan. Dengan adanya kurikulum baru ini, diharapkan lulusan sekolah di Indonesia tidak hanya unggul secara akademis, tetapi juga memiliki karakter kuat dan keterampilan yang siap bersaing di dunia kerja maupun pendidikan lanjutan.', '¿Qué es el aprendizaje socioemocional_.jpg', '2026-04-05 00:00:00', 'publish', 5, NULL, 7),
(16, 'Industri Film Lokal Tunjukkan Tren Positif, Penonton Semakin Antusias', 'Jakarta, 5 April 2026 – Industri perfilman Indonesia kembali menunjukkan perkembangan yang menggembirakan. Hal ini terlihat dari meningkatnya jumlah penonton film lokal yang tayang di bioskop dalam beberapa waktu terakhir. Film-film dengan berbagai genre seperti drama, komedi, hingga aksi berhasil menarik perhatian masyarakat, khususnya kalangan muda. Selain cerita yang lebih variatif, kualitas produksi yang semakin baik juga menjadi faktor utama meningkatnya minat penonton. Para pelaku industri menilai bahwa dukungan masyarakat terhadap film lokal sangat penting untuk keberlangsungan industri ini. Selain itu, kehadiran platform digital juga turut membantu memperluas jangkauan distribusi film. Dengan tren positif ini, diharapkan industri hiburan Indonesia dapat terus berkembang dan mampu bersaing di tingkat internasional.', 'download (13).jpg', '2026-04-05 00:00:00', 'publish', 7, NULL, 47),
(17, 'Tim Nasional Indonesia Matangkan Persiapan Jelang Turnamen Internasional', 'Jakarta, 5 April 2026 – Tim Nasional Indonesia terus mematangkan persiapan menjelang keikutsertaan dalam turnamen internasional yang akan segera digelar. Latihan intensif dilakukan untuk meningkatkan kondisi fisik, strategi permainan, serta kekompakan antar pemain. Pelatih timnas menyatakan bahwa seluruh pemain menunjukkan perkembangan yang positif selama masa latihan. Beberapa pemain muda juga mendapatkan kesempatan untuk bergabung dan diharapkan mampu memberikan kontribusi maksimal bagi tim.Selain latihan di dalam negeri, timnas ju al ini dilakukan untuk mengukur kemampuan tim sebelum bertanding di ajang resmi. Dukungan dari masyarakat Indonesia diharapkan dapat menjadi motivasi tambahan bagi para pemain untuk memberikan performa terbaik dan mengharumkan nama bangsa di kancah internasional.', 'Gym lesson.jpg', '2026-04-05 00:00:00', 'publish', 2, NULL, 5),
(18, 'Harga Kebutuhan Pokok Naik, Pemerintah Siapkan Langkah Stabilitas Pasar', 'Bandung, 5 April 2026 – Menjelang hari besar keagamaan, harga sejumlah kebutuhan pokok di pasar tradisional mengalami kenaikan yang cukup signifikan. Kenaikan ini dipicu oleh meningkatnya permintaan masyarakat serta distribusi barang yang belum sepenuhnya stabil. Beberapa komoditas utama seperti beras, minyak goreng, gula, dan telur menjadi yang paling terdampak. Para pedagang mengaku kenaikan harga sudah terjadi secara bertahap sejak awal bulan dan diperkirakan akan terus meningkat hingga puncak hari besar. Pemerintah melalui dinas perdagangan setempat menyatakan akan melakukan berbagai langkah untuk menjaga stabilitas harga, salah satunya melalui operasi pasar dan pengawasan distribusi barang. Langkah ini diharapkan dapat membantu masyarakat mendapatkan kebutuhan pokok dengan harga yang terjangkau. Di sisi lain, para ekonom menilai bahwa kondisi ini merupakan fenomena yang kerap terjadi setiap tahun. Oleh karena itu, diperlukan strategi jangka panjang untuk mengatasi fluktuasi harga agar tidak memberatkan masyarakat.', 'download (14).jpg', '2026-04-05 00:00:00', 'publish', 6, NULL, 41),
(19, 'Cuaca Ekstrem Melanda Sejumlah Wilayah, Pemerintah Imbau Warga Tingkatkan Kewaspadaan', 'Jakarta, 5 April 2026 – Cuaca ekstrem berupa hujan lebat disertai angin kencang melanda sejumlah wilayah di Indonesia dalam beberapa hari terakhir. Kondisi ini menimbulkan berbagai dampak, mulai dari genangan air hingga potensi bencana seperti banjir dan tanah longsor. Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) menyatakan bahwa fenomena ini dipengaruhi oleh perubahan pola cuaca yang tidak menentu. Masyarakat yang tinggal di daerah rawan bencana diminta untuk meningkatkan kewaspadaan serta memantau informasi cuaca secara berkala. Sejumlah pemerintah daerah telah mengambil langkah antisipasi dengan menyiagakan tim penanggulangan bencana serta melakukan evakuasi di beberapa titik yang dianggap berisiko tinggi. Selain itu, warga juga diimbau untuk tidak membuang sampah sembarangan agar saluran air tetap lancar. Dengan kondisi cuaca yang masih berpotensi ekstrem dalam beberapa hari ke depan, masyarakat diharapkan dapat lebih berhati-hati dan mengikuti arahan dari pihak berwenang.', 'A poster illustrating the impact of natural disasters on communities and the environment emphasizing _ Premium AI-generated image.jpg', '2026-04-05 00:00:00', 'publish', 3, NULL, 2),
(20, 'Tim Basket Indonesia Tunjukkan Performa Gemilang di Turnamen Regional Asia', 'Jakarta, 5 April 2026 – Tim nasional bola basket Indonesia menunjukkan performa impresif dalam ajang turnamen regional Asia yang berlangsung pekan ini. Dalam pertandingan yang berlangsung sengit, Indonesia berhasil meraih kemenangan penting atas lawan-lawan tangguh dari berbagai negara. Pada laga terakhir, tim Indonesia tampil solid dengan kerja sama tim yang baik serta strategi permainan yang efektif. Para pemain mampu memanfaatkan setiap peluang untuk mencetak poin, sekaligus memperkuat pertahanan dari serangan lawan. Pelatih tim nasional menyampaikan apresiasinya terhadap kerja keras para pemain yang telah menjalani latihan intensif sebelum turnamen dimulai. Ia menilai bahwa peningkatan performa ini merupakan hasil dari disiplin dan kekompakan tim selama masa persiapan. Salah satu pemain andalan Indonesia juga menjadi sorotan setelah berhasil mencetak poin tertinggi dalam pertandingan tersebut. Penampilannya yang konsisten dinilai menjadi faktor kunci kemenangan tim. Selain itu, dukungan dari masyarakat Indonesia turut memberikan semangat tambahan bagi para pemain untuk tampil maksimal di setiap pertandingan. Antusiasme penonton, baik yang hadir langsung maupun yang menyaksikan melalui siaran daring, menjadi motivasi tersendiri bagi tim. Keberhasilan ini membuka peluang besar bagi Indonesia untuk melaju ke babak selanjutnya. Tim nasional diharapkan mampu mempertahankan performa terbaiknya dan terus mengharumkan nama bangsa di kancah internasional.', 'About Us - NOODLS_COM.jpg', '2026-04-05 00:00:00', 'publish', 2, NULL, 52),
(21, 'Atlet Lari Indonesia Cetak Prestasi Membanggakan di Ajang Internasional', 'akarta, 5 April 2026 – Atlet lari Indonesia kembali menorehkan prestasi membanggakan di ajang kompetisi internasional yang berlangsung pekan ini. Dalam perlombaan yang diikuti oleh peserta dari berbagai negara, atlet Indonesia berhasil meraih posisi podium setelah menunjukkan performa yang konsisten sejak awal lomba. Pada nomor lari jarak menengah 1500 meter, perwakilan Indonesia tampil percaya diri dengan strategi menjaga ritme di awal dan meningkatkan kecepatan pada putaran terakhir. Hasilnya, ia berhasil finis di posisi dua dengan catatan waktu yang mengesankan. Pelatih tim menyampaikan bahwa keberhasilan ini merupakan hasil dari latihan intensif yang telah dijalani selama beberapa bulan terakhir. Program latihan yang terstruktur serta fokus pada peningkatan stamina dan kecepatan menjadi kunci utama dalam pencapaian tersebut. Selain itu, faktor mental juga dinilai sangat berpengaruh dalam pertandingan. Atlet dituntut untuk tetap fokus dan tenang meskipun berada di bawah tekanan dari lawan-lawan yang memiliki pengalaman internasional. Prestasi ini mendapat apresiasi dari berbagai pihak, termasuk pemerintah dan masyarakat yang terus memberikan dukungan kepada para atlet nasional. Diharapkan, pencapaian ini dapat menjadi motivasi bagi generasi muda Indonesia untuk lebih aktif dalam bidang olahraga, khususnya cabang atletik. Ke depan, atlet tersebut dijadwalkan akan mengikuti beberapa kompetisi lainnya sebagai bagian dari persiapan menuju kejuaraan yang lebih besar. Dengan kerja keras dan dukungan yang terus mengalir, Indonesia optimis dapat meraih prestasi yang lebih tinggi di masa mendatang.', 'Olympic games sports background with copy space for text _ Premium AI-generated image.jpg', '2026-04-05 00:00:00', 'publish', 2, NULL, 0),
(22, 'Atlet Renang Indonesia Tunjukkan Performa Cemerlang di Kejuaraan Internasional', 'Jakarta, 5 April 2026 – Atlet renang Indonesia kembali menunjukkan prestasi membanggakan dalam ajang kejuaraan internasional yang berlangsung pekan ini. Dalam kompetisi yang diikuti oleh perenang dari berbagai negara, perwakilan Indonesia berhasil meraih medali dan mencatatkan waktu terbaiknya. Pada nomor gaya bebas 100 meter, atlet Indonesia tampil dengan percaya diri sejak awal pertandingan. Dengan start yang cepat dan teknik renang yang efisien, ia mampu bersaing ketat dengan para pesaing hingga garis finis. Hasilnya, ia berhasil mengamankan posisi tiga besar dan membawa pulang medali perunggu. Pelatih tim renang nasional menyampaikan bahwa pencapaian tersebut merupakan hasil dari latihan yang disiplin dan konsisten. Program latihan yang difokuskan pada peningkatan kecepatan, teknik pernapasan, serta daya tahan tubuh menjadi faktor utama dalam keberhasilan atlet. Selain itu, kondisi mental atlet juga dinilai sangat berpengaruh dalam pertandingan. Kemampuan untuk tetap fokus dan mengendalikan tekanan menjadi kunci penting dalam menghadapi kompetisi tingkat internasional. Keberhasilan ini mendapat apresiasi dari berbagai pihak, termasuk pemerintah dan masyarakat yang terus memberikan dukungan kepada para atlet nasional. Prestasi tersebut diharapkan dapat menjadi motivasi bagi generasi muda Indonesia untuk menekuni olahraga renang dan mengembangkan potensi yang dimiliki.Ke depan, tim renang Indonesia akan terus mempersiapkan diri untuk menghadapi kompetisi berikutnya, termasuk ajang yang lebih besar di tingkat dunia. Dengan kerja keras dan du kungan yang berkelanjutan, Indonesia optimis dapat meraih prestasi yang lebih tinggi di cabang olahraga renang.', 'Tumblr.jpg', '2026-04-05 00:00:00', 'publish', 2, NULL, 1),
(23, 'Pemerintah Tingkatkan Program Kebersihan Lingkungan di Perkotaan', 'Jakarta, 5 April 2026 – Pemerintah terus meningkatkan program kebersihan lingkungan di berbagai wilayah perkotaan sebagai upaya menciptakan lingkungan yang sehat dan nyaman bagi masyarakat. Program ini melibatkan berbagai pihak, mulai dari pemerintah daerah hingga komunitas masyarakat.\r\nKegiatan yang dilakukan meliputi pembersihan saluran air, pengelolaan sampah terpadu, serta sosialisasi pentingnya menjaga kebersihan lingkungan. Pemerintah juga menyediakan fasilitas pendukung seperti tempat sampah terpilah dan armada pengangkut sampah yang memadai. Menurut pihak terkait, kesadaran masyarakat menjadi faktor utama dalam keberhasilan program ini. Oleh karena itu, edukasi mengenai pentingnya menjaga lingkungan terus digencarkan melalui berbagai media. Dengan adanya program ini, diharapkan kualitas lingkungan di perkotaan dapat meningkat dan risiko penyakit akibat lingkungan kotor dapat diminimalisir.', 'cleanliness drive_.jpg', '2026-04-05 00:00:00', 'publish', 3, NULL, 0),
(24, 'Pembangunan Infrastruktur Dipercepat, Dorong Pertumbuhan Ekonomi Daerah', 'Jakarta, 5 April 2026 – Pemerintah terus mempercepat pembangunan infrastruktur di berbagai wilayah Indonesia sebagai upaya mendorong pertumbuhan ekonomi dan meningkatkan kesejahteraan masyarakat. Proyek-proyek strategis seperti jalan tol, jembatan, serta pengembangan transportasi umum menjadi fokus utama dalam program pembangunan nasional. Dalam beberapa tahun terakhir, pembangunan infrastruktur dinilai telah memberikan dampak positif terhadap konektivitas antarwilayah. Akses yang lebih mudah memungkinkan distribusi barang dan jasa menjadi lebih cepat dan efisien, sehingga turut mendorong aktivitas ekonomi di daerah. Menteri terkait menyampaikan bahwa percepatan pembangunan ini tidak hanya berfokus pada kota besar, tetapi juga menjangkau daerah terpencil dan tertinggal. Hal ini dilakukan untuk menciptakan pemerataan pembangunan serta mengurangi kesenjangan antarwilayah. Selain itu, proyek infrastruktur juga membuka lapangan kerja baru bagi masyarakat setempat. Banyak tenaga kerja lokal yang terlibat dalam proses pembangunan, sehingga memberikan dampak langsung terhadap peningkatan pendapatan masyarakat. Meski demikian, pemerintah tetap memperhatikan aspek lingkungan dalam setiap proyek yang dijalankan. Analisis dampak lingkungan dilakukan guna memastikan pembangunan berjalan secara berkelanjutan dan tidak merusak ekosistem. Dengan adanya percepatan pembangunan infrastruktur ini, pemerintah optimis bahwa pertumbuhan ekonomi nasional akan semakin meningkat serta mampu bersaing di tingkat global.', 'работа вахта водитель самосвала.jpg', '2026-04-05 00:00:00', 'publish', 3, NULL, 0),
(25, 'Program Beasiswa Diperluas, Buka Akses Pendidikan bagi Siswa Berprestasi', 'akarta, 5 April 2026 – Pemerintah memperluas program beasiswa nasional guna memberikan kesempatan yang lebih besar bagi siswa berprestasi dari berbagai daerah untuk melanjutkan pendidikan ke jenjang yang lebih tinggi. Program ini mencakup bantuan biaya pendidikan, biaya hidup, hingga dukungan pengembangan diri bagi penerima beasiswa. Tidak hanya untuk siswa di perkotaan, program ini juga menyasar pelajar dari daerah terpencil yang memiliki potensi akademik tinggi.\r\nMenurut pihak kementerian terkait, langkah ini bertujuan untuk menciptakan pemerataan akses pendidikan serta mengurangi kesenjangan sosial di masyarakat. Dengan adanya beasiswa, diharapkan tidak ada lagi siswa yang terhambat melanjutkan pendidikan karena faktor ekonomi.\r\nMeski demikian, proses seleksi tetap dilakukan secara ketat untuk memastikan bahwa bantuan diberikan kepada siswa yang benar-benar layak dan berkomitmen tinggi terhadap pendidikan.', 'Medal – zdjęcia_ Pobierz darmowe obrazy wysokiej jakości _ Freepik.jpg', '2026-04-05 00:00:00', 'publish', 5, NULL, 1),
(26, 'Peran Orang Tua Dinilai Penting dalam Mendukung Keberhasilan Belajar Siswa', 'Surabaya, 5 April 2026 – Peran orang tua dalam mendukung proses belajar siswa dinilai semakin penting, terutama di tengah perubahan sistem pendidikan yang semakin dinamis. Keterlibatan orang tua dalam memantau perkembangan akademik anak, memberikan motivasi, serta menciptakan lingkungan belajar yang nyaman di rumah menjadi faktor yang berpengaruh terhadap keberhasilan siswa. Sejumlah sekolah juga mulai menjalin komunikasi yang lebih intens dengan orang tua melalui berbagai program, seperti pertemuan rutin dan laporan perkembangan belajar siswa secara berkala Para ahli pendidikan menyatakan bahwa sinergi antara sekolah dan orang tua dapat memberikan dampak positif yang signifikan terhadap prestasi dan perkembangan karakter siswa. Dengan dukungan yang baik dari keluarga, diharapkan siswa dapat belajar dengan lebih optimal dan mencapai hasil yang maksimal.', 'How Do I Create A Comprehensive Family Survival Plan_ - Grid Down Guide.jpg', '2026-04-05 00:00:00', 'publish', 5, NULL, 0),
(27, 'Sekolah Tingkatkan Program Bimbingan Konseling untuk Dukung Kesehatan Mental Siswa', 'Yogyakarta, 5 April 2026 – Sekolah-sekolah di Indonesia mulai meningkatkan peran layanan bimbingan dan konseling (BK) sebagai upaya mendukung kesehatan mental siswa. Program ini bertujuan untuk membantu siswa dalam menghadapi berbagai permasalahan, baik yang berkaitan dengan akademik maupun kehidupan pribadi. Konselor sekolah memberikan pendampingan serta solusi yang tepat agar siswa dapat mengatasi tekanan yang dihadapi.Dalam beberapa tahun terakhir, kesadaran akan pentingnya kesehatan mental di lingkungan pendidikan semakin meningkat. Sekolah tidak hanya fokus pada prestasi akademik, tetapi juga kesejahteraan psikologis siswa.Melalui program bimbingan konseling yang optimal, diharapkan siswa dapat merasa lebih nyaman dalam lingkungan sekolah serta mampu berkembang dengan baik secara emosional dan sosial.', 'download (16).jpg', '2026-04-05 00:00:00', 'publish', 5, NULL, 0),
(28, 'Keamanan Data Digital Menjadi Perhatian Utama di Era Modern', 'Bandung, 5 April 2026 – Keamanan data digital menjadi salah satu isu penting di era teknologi saat ini. Meningkatnya penggunaan internet dan layanan digital membuat risiko kebocoran data semakin tinggi. Berbagai kasus peretasan dan penyalahgunaan data pribadi menjadi perhatian serius bagi masyarakat dan pemerintah. Oleh karena itu, perlindungan data menjadi hal yang sangat penting untuk diperhatikan. Perusahaan teknologi mulai meningkatkan sistem keamanan mereka dengan menggunakan enkripsi data serta sistem autentikasi berlapis. Sementara itu, pengguna juga diimbau untuk lebih berhati-hati dalam membagikan informasi pribadi di internet.Dengan kesadaran yang tinggi terhadap keamanan data, diharapkan masyarakat dapat terhindar dari berbagai ancaman digital yang merugikan.', 'Read the article on Cybersecurity Risks for CIA Part 3 -.jpg', '2026-04-05 00:00:00', 'publish', 1, NULL, 0),
(29, 'Perkembangan Internet of Things (IoT) Dorong Kehidupan Lebih Praktis', 'Surabaya, 5 April 2026 – Teknologi Internet of Things (IoT) semakin berkembang dan mulai diterapkan dalam berbagai aspek kehidupan sehari-hari. IoT memungkinkan berbagai perangkat terhubung dan saling berkomunikasi melalui internet. Contoh penerapan IoT dapat ditemukan pada rumah pintar (smart home), di mana perangkat seperti lampu, kamera keamanan, hingga alat elektronik dapat dikendalikan melalui smartphone. Hal ini memberikan kemudahan dan kenyamanan bagi pengguna. Selain di rumah tangga, IoT juga digunakan di sektor industri, kesehatan, dan transportasi untuk meningkatkan efisiensi dan produktivitas. Teknologi ini dinilai mampu menjadi solusi dalam menghadapi berbagai tantangan di era digital.Meski memiliki banyak manfaat, penggunaan IoT juga memerlukan perhatian terhadap aspek keamanan agar tidak disalahgunakan oleh pihak yang tidak bertanggung jawab.', 'Applications Of IoT.jpg', '2026-04-05 00:00:00', 'publish', 1, NULL, 3),
(30, 'Kesadaran Masyarakat terhadap Gaya Hidup Sehat Terus Meningkat', 'Jakarta, 5 April 2026 – Kesadaran masyarakat Indonesia terhadap pentingnya menjaga kesehatan semakin meningkat dalam beberapa tahun terakhir. Hal ini terlihat dari semakin banyaknya masyarakat yang rutin berolahraga dan memperhatikan pola makan sehat. Berbagai fasilitas olahraga seperti taman kota, jalur jogging, dan pusat kebugaran mulai ramai dikunjungi oleh masyarakat dari berbagai kalangan usia. Selain itu, tren konsumsi makanan sehat juga semakin berkembang. Para ahli kesehatan menilai bahwa perubahan gaya hidup ini merupakan langkah positif dalam meningkatkan kualitas hidup masyarakat serta mencegah berbagai penyakit. Pemerintah pun terus mendukung gerakan hidup sehat melalui berbagai program dan kampanye yang melibatkan masyarakat secara luas.', 'Proven Daily Habits That Could Add Decades to Your Life.jpg', '2026-04-05 00:00:00', 'publish', 3, NULL, 4),
(31, 'Pertumbuhan UMKM Meningkat, Jadi Penopang Ekonomi Nasional', 'Jakarta, 5 April 2026 – Usaha Mikro, Kecil, dan Menengah (UMKM) terus menunjukkan pertumbuhan yang positif dan menjadi salah satu pilar utama dalam menopang perekonomian nasional. Kontribusi UMKM terhadap Produk Domestik Bruto (PDB) dinilai semakin signifikan dari tahun ke tahun. Pemerintah terus mendorong pengembangan UMKM melalui berbagai program, seperti pelatihan kewirausahaan, akses pembiayaan, serta digitalisasi usaha. Langkah ini bertujuan untuk meningkatkan daya saing pelaku UMKM di tengah persaingan pasar yang semakin ketat. Selain itu, pemanfaatan platform digital juga membantu pelaku usaha dalam memperluas jangkauan pemasaran hingga ke tingkat nasional maupun internasional. Hal ini membuka peluang besar bagi UMKM untuk berkembang lebih pesat. Meski demikian, tantangan seperti keterbatasan modal dan akses pasar masih menjadi kendala yang perlu diatasi secara bertahap.', 'pasar tradisional.jpg', '2026-04-05 00:00:00', 'publish', 6, NULL, 1),
(32, 'Digitalisasi Pembayaran Dorong Transaksi Non-Tunai di Masyarakat', 'Jakarta, 5 April 2026 – Tren penggunaan pembayaran digital di Indonesia terus meningkat seiring dengan perkembangan teknologi dan perubahan gaya hidup masyarakat. Transaksi non-tunai kini menjadi pilihan utama dalam berbagai aktivitas, mulai dari belanja hingga pembayaran layanan. Berbagai metode pembayaran digital seperti dompet elektronik (e-wallet) dan mobile banking semakin banyak digunakan karena dinilai lebih praktis, cepat, dan aman. Hal ini juga didukung oleh banyaknya promo dan kemudahan akses yang ditawarkan oleh penyedia layanan. Pemerintah dan Bank Indonesia terus mendorong digitalisasi sistem pembayaran guna menciptakan ekosistem ekonomi yang lebih modern dan efisien. Selain itu, digitalisasi juga dinilai mampu meningkatkan transparansi dalam transaksi keuangan. Dengan meningkatnya penggunaan pembayaran digital, diharapkan sistem ekonomi di Indonesia dapat menjadi lebih inklusif dan mampu menjangkau seluruh lapisan masyarakat.', 'Man doing payment with QR scanner.jpg', '2026-04-05 00:00:00', 'publish', 6, NULL, 2),
(33, 'Harga Pangan Mulai Stabil, Distribusi Jadi Faktor Penentu', 'Bandung, 5 April 2026 – Harga sejumlah bahan pangan di pasar tradisional mulai menunjukkan tanda-tanda stabil setelah sebelumnya mengalami kenaikan dalam beberapa pekan terakhir. Stabilitas ini dipengaruhi oleh membaiknya distribusi barang dari daerah produsen ke pasar-pasar utama. Para pedagang menyebutkan bahwa pasokan barang kini sudah lebih lancar dibandingkan sebelumnya. Komoditas seperti beras, cabai, dan telur mulai kembali ke harga yang lebih terjangkau meskipun masih terdapat fluktuasi di beberapa daerah. Pemerintah daerah terus melakukan pengawasan terhadap jalur distribusi untuk memastikan tidak terjadi penimbunan atau keterlambatan pengiriman barang. Selain itu, koordinasi dengan para distributor juga ditingkatkan agar pasokan tetap terjaga. Menurut pengamat ekonomi, kelancaran distribusi menjadi faktor utama dalam menjaga stabilitas harga pangan. Jika distribusi berjalan dengan baik, maka lonjakan harga dapat ditekan dan daya beli masyarakat tetap terjaga. Masyarakat diimbau untuk tetap bijak dalam berbelanja dan tidak melakukan pembelian secara berlebihan guna menjaga keseimbangan pasar.', 'Peran Supply Chain Financing dalam Mendukung Pembiayaan UKM.jpg', '2026-04-05 00:00:00', 'publish', 6, NULL, 0),
(34, 'Event Festival Seni dan Budaya Tarik Ribuan Pengunjung', 'Bali, 5 April 2026 – Festival seni dan budaya yang digelar di Bali berhasil menarik perhatian ribuan pengunjung dari berbagai daerah. Acara ini menampilkan beragam pertunjukan seni, mulai dari tari tradisional, musik, hingga pameran karya seni. Kegiatan ini tidak hanya menjadi ajang hiburan, tetapi juga sarana untuk melestarikan budaya lokal agar tetap dikenal oleh generasi muda. Para seniman dan pelaku budaya memanfaatkan kesempatan ini untuk memperkenalkan karya mereka kepada masyarakat luas. Selain itu, festival ini juga memberikan dampak positif terhadap sektor pariwisata dan ekonomi lokal, terutama bagi pelaku usaha kecil di sekitar lokasi acara. Dengan tingginya antusiasme masyarakat, diharapkan kegiatan serupa dapat terus diselenggarakan secara rutin sebagai bagian dari upaya pelestarian budaya dan pengembangan industri kreatif.', 'Tari Kecak Bali.jpg', '2026-04-05 00:00:00', 'publish', 7, NULL, 0),
(35, 'Fenomena “Healing Trip” Jadi Gaya Hidup Baru di Kalangan Anak Muda', 'Bandung, 5 April 2026 Tren “healing trip” atau perjalanan untuk melepas penat kini semakin populer di kalangan anak muda. Banyak yang membagikan pengalaman mereka berlibur ke alam terbuka melalui media sosial.Destinasi seperti pegunungan, pantai, dan tempat wisata alam menjadi pilihan utama untuk mencari ketenangan dan mengurangi stres. Konten-konten perjalanan ini pun banyak menarik perhatian warganet.Selain sebagai hiburan, tren ini juga berdampak positif terhadap sektor pariwisata lokal. Banyak tempat wisata yang mengalami peningkatan jumlah pengunjung berkat viralnya konten di media sosial.', 'mountain tracking with friends.jpg', '2026-04-05 00:00:00', 'publish', 7, NULL, 4),
(36, 'Program Makan Bergizi Gratis Diterapkan, Dukung Kesehatan dan Prestasi Siswa', 'Jakarta, 5 April 2026 – Pemerintah mulai menerapkan program Makan Bergizi Gratis (MBG) di berbagai sekolah sebagai upaya meningkatkan kualitas kesehatan dan konsentrasi belajar siswa. Program ini menjadi salah satu langkah strategis dalam mendukung generasi muda yang sehat dan  berprestasi.Melalui program ini, siswa mendapatkan makanan bergizi secara gratis setiap hari sekolah. Menu yang disediakan telah disesuaikan dengan kebutuhan nutrisi anak, mencakup karbohidrat, protein, vitamin, dan mineral yang seimbang. Pihak sekolah menyambut baik kebijakan ini karena dinilai mampu membantu siswa yang sebelumnya datang ke sekolah tanpa sarapan. Dengan terpenuhinya kebutuhan gizi, siswa diharapkan dapat lebih fokus dalam mengikuti kegiatan belajar mengajar. Selain berdampak pada kesehatan, program ini juga dinilai mampu meningkatkan kehadiran siswa di sekolah. Banyak orang tua merasa terbantu karena beban pengeluaran untuk konsumsi anak menjadi berkurang.Meski demikian, pelaksanaan program MBG masih menghadapi sejumlah tantangan, seperti distribusi makanan, pengawasan kualitas, serta kesiapan fasilitas di beberapa daerah. Pemerintah menyatakan akan terus melakukan evaluasi dan perbaikan agar program ini dapat berjalan optimal.Dengan adanya program Makan Bergizi Gratis, diharapkan kualitas pendidikan di Indonesia dapat meningkat, seiring dengan terciptanya generasi yang sehat, cerdas, dan siap menghadapi masa depan.', 'MBG.jpg', '2026-04-05 00:00:00', 'draft', 5, NULL, 0),
(37, 'Atlet Bulu Tangkis Indonesia Tampil Gemilang di Turnamen Internasional', 'Jakarta, 5 April 2026 – Atlet bulu tangkis Indonesia kembali menunjukkan performa impresif dalam ajang turnamen internasional yang berlangsung pekan ini. Dalam pertandingan yang berlangsung ketat, wakil Indonesia berhasil melaju hingga babak final dan meraih hasil membanggakan. Pada nomor tunggal putra, perwakilan Indonesia tampil dominan sejak babak awal dengan permainan agresif dan strategi yang matang. Ia berhasil mengalahkan beberapa pemain unggulan dari negara lain sebelum akhirnya memastikan tempat di partai puncak. Sementara itu, pada sektor ganda, pasangan Indonesia juga menunjukkan kerja sama yang solid. Kombinasi serangan cepat dan pertahanan yang kuat menjadi kunci keberhasilan mereka dalam menghadapi lawan-lawannya. Pelatih tim nasional menyampaikan bahwa hasil ini merupakan buah dari kerja keras para atlet selama menjalani program latihan intensif. Ia juga menekankan pentingnya menjaga konsistensi permainan untuk menghadapi kompetisi selanjutnya. Dukungan dari masyarakat Indonesia turut memberikan semangat tambahan bagi para atlet untuk tampil maksimal di setiap pertandingan. Antusiasme publik terhadap cabang olahraga bulu tangkis dinilai masih sangat tinggi. Dengan pencapaian ini, Indonesia kembali menegaskan posisinya sebagai salah satu kekuatan utama dalam dunia bulu tangkis internasional. Diharapkan prestasi ini dapat terus berlanjut dan menginspirasi generasi muda untuk menekuni olahraga tersebut.', 'Background Kok.jpg', '2026-04-05 00:00:00', 'publish', 2, NULL, 0),
(38, 'Kesadaran Masyarakat terhadap Kebersihan Lingkungan Semakin Meningkat', 'Pasartanahtinggi, 5 April 2026 – Kesadaran masyarakat dalam menjaga kebersihan lingkungan menunjukkan peningkatan dalam beberapa waktu terakhir. Hal ini terlihat dari semakin banyaknya kegiatan kerja bakti serta partisipasi warga dalam menjaga kebersihan di lingkungan tempat tinggal. Berbagai inisiatif dilakukan, mulai dari program gotong royong rutin, penyediaan tempat sampah di area publik, hingga kampanye pengurangan penggunaan plastik sekali pakai. Upaya ini tidak hanya dilakukan oleh pemerintah, tetapi juga didukung oleh komunitas dan warga setempat. Salah satu warga mengungkapkan bahwa perubahan ini terjadi karena meningkatnya pemahaman akan pentingnya lingkungan yang bersih dan sehat. “Sekarang warga lebih peduli, tidak hanya menunggu petugas kebersihan, tapi ikut menjaga bersama,” ujarnya. Selain itu, beberapa sekolah juga mulai mengajarkan pentingnya menjaga lingkungan sejak dini kepada para siswa. Edukasi ini diharapkan dapat membentuk kebiasaan positif yang berkelanjutan. Pemerintah daerah mengapresiasi partisipasi masyarakat tersebut dan berkomitmen untuk terus mendukung program kebersihan melalui penyediaan fasilitas dan sosialisasi yang berkelanjutan. Dengan meningkatnya kesadaran ini, diharapkan lingkungan yang bersih dan sehat dapat terus terjaga demi kenyamanan dan kualitas hidup masyarakat yang lebih baik.', 'El Río y los Cinco Amigos.jpg', '2026-04-05 00:00:00', 'publish', 3, NULL, 1),
(41, 'Sektor Pariwisata Bangkit, Kunjungan Wisatawan Alami Peningkatan', 'Jakarta, 5 April 2026 – Sektor pariwisata Indonesia menunjukkan tanda-tanda kebangkitan dengan meningkatnya jumlah kunjungan wisatawan dalam beberapa waktu terakhir. Berbagai destinasi wisata kembali ramai dikunjungi, baik oleh wisatawan domestik maupun mancanegara.Peningkatan ini didorong oleh membaiknya kondisi ekonomi serta berbagai program promosi yang dilakukan oleh pemerintah dan pelaku industri pariwisata. Selain itu, pengembangan infrastruktur dan fasilitas wisata juga turut berkontribusi dalam menarik minat pengunjung. Destinasi wisata alam, budaya, dan kuliner menjadi pilihan utama bagi wisatawan. Banyak daerah yang memanfaatkan momentum ini untuk memperkenalkan potensi lokal mereka, sehingga memberikan dampak positif terhadap perekonomian masyarakat setempat. Pemerintah terus mendorong pengembangan sektor pariwisata dengan tetap memperhatikan aspek keberlanjutan dan pelestarian lingkungan. Edukasi kepada masyarakat dan pelaku usaha juga dilakukan agar kegiatan pariwisata berjalan secara bertanggung jawab. Dengan tren positif ini, sektor pariwisata diharapkan dapat menjadi salah satu penggerak utama pertumbuhan ekonomi nasional serta membuka lebih banyak lapangan kerja bagi masyarakat.', 'download (18).jpg', '2026-04-05 00:00:00', 'publish', 3, NULL, 1);

-- --------------------------------------------------------

--
-- Struktur dari tabel `kategori`
--

CREATE TABLE `kategori` (
  `id_kategori` int(11) NOT NULL,
  `nama_kategori` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `kategori`
--

INSERT INTO `kategori` (`id_kategori`, `nama_kategori`) VALUES
(1, 'Teknologi'),
(2, 'Olahraga'),
(3, 'Berita Utama'),
(5, 'Pendidikan'),
(6, 'Ekonomi'),
(7, 'Hiburan');

-- --------------------------------------------------------

--
-- Struktur dari tabel `users`
--

CREATE TABLE `users` (
  `id_user` int(11) NOT NULL,
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `role` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `users`
--

INSERT INTO `users` (`id_user`, `username`, `password`, `role`) VALUES
(1, 'admin', '123', 'admin');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `artikel`
--
ALTER TABLE `artikel`
  ADD PRIMARY KEY (`id_artikel`);

--
-- Indeks untuk tabel `kategori`
--
ALTER TABLE `kategori`
  ADD PRIMARY KEY (`id_kategori`);

--
-- Indeks untuk tabel `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id_user`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `artikel`
--
ALTER TABLE `artikel`
  MODIFY `id_artikel` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT untuk tabel `kategori`
--
ALTER TABLE `kategori`
  MODIFY `id_kategori` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT untuk tabel `users`
--
ALTER TABLE `users`
  MODIFY `id_user` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
